name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./build-docker.sh
      - uses: actions/upload-artifact@v2
        with:
          name: JRE
          path: |
            *.ipk
            jre_*.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - name: Create GitHub Release
        run: gh release create "${GITHUB_REF#refs/tags/}" **/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
