name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./build-docker.sh
      - uses: actions/upload-artifact@v4
        with:
          name: JRE
          path: |
            *.ipk
            jre_*.tar.gz

  release-github:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Create GitHub Release
        if: github.repository_owner == 'wpilibsuite' && startsWith(github.ref, 'refs/tags/v')
        run: gh release create "${GITHUB_REF#refs/tags/}" JRE/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-artifactory:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jfrog/setup-jfrog-cli@v3
        if: github.repository_owner == 'wpilibsuite' && startsWith(github.ref, 'refs/tags/v')
        env:
          JF_ENV_1: ${{ secrets.ARTIFACTORY_CLI_SECRET }}
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Generate Maven
        run: |
          source versions.sh
          mvn install:install-file -DlocalRepositoryPath=mvn -Dfile=JRE/${IPK_NAME} -DgroupId=edu.wpi.first.jdk -DartifactId=roborio-${YEAR} -Dversion=${VER} -Dpackaging=ipk -DgeneratePom=true
      - name: Upload
        if: github.repository_owner == 'wpilibsuite' && startsWith(github.ref, 'refs/tags/v')
        working-directory: mvn
        run: jfrog rt u "*" thirdparty-mvn-release/ --exclusions="*maven-metadata-local*"
      - uses: actions/upload-artifact@v4
        with:
          name: Maven
          path: mvn
